@startuml
'https://plantuml.com/class-diagram

class PortIF
{
+ __init__(port, )
}
class CommandIF

class Command {
+__init__(cmd)
+help()
+build()

}

class SerialDevice
{
+port
+
+setup()
+send(command, parameter, )
}

@enduml